import React, { createContext, useContext, useMemo, useState } from 'react';

const dictionaries = {
  en: {
    languageLabel: 'Language',
    nav: {
      home: 'Home',
      about: 'About',
      services: 'Services',
      articles: 'Articles',
      gallery: 'Gallery',
      contact: 'Contact',
    },
    common: {
      bookAppointment: 'Book Appointment',
      callClinic: 'Call Clinic',
      whatsapp: 'WhatsApp',
      contact: 'Contact',
      social: 'Social',
      readArticle: 'Read article',
      readArticles: 'Read articles',
      viewAllServices: 'View all services',
      submitAppointment: 'Submit Appointment Request',
      submitting: 'Submitting...',
    },
    clinic: {
      tagline: 'Fertility, women care, and advanced laparoscopy',
      emergency: 'Compassionate fertility and gynecology care',
      footer: 'Patient-first fertility, gynecology, and laparoscopy care with accessible appointments, clear counseling, and thoughtful follow-up.',
    },
    home: {
      title: 'Eva Fertility & Laparoscopy',
      subtitle: 'Specialist fertility, gynecology, IVF guidance, pregnancy planning, and minimally invasive laparoscopy care with Dr. Raveendra Gondhali in Thergaon, Pune.',
      programsEyebrow: 'Care programs',
      programsTitle: 'Fertility and women care services',
      successEyebrow: 'Patient thoughts',
      successTitle: 'Our Success Stories',
      successSubtitle: 'Anonymized patient feedback focused on communication, comfort, and guided follow-up care.',
      articlesEyebrow: 'Articles',
      articlesTitle: 'Fertility and women wellness notes',
    },
    about: {
      eyebrow: 'About us',
      title: 'Fertility and gynecology care led by Dr. Raveendra Gondhali',
      body: 'Eva Fertility & Laparoscopy offers fertility consultation, infertility treatment planning, IVF and IUI guidance, PCOS care, pregnancy support, hysteroscopy, and laparoscopy services at Silver Birch Multispeciality Hospital, Thergaon. Care is built around privacy, careful listening, and clear next steps.',
      cards: ['25+ years experience', 'OBGYN and IVF specialist', 'Clear follow-up care'],
    },
    servicesPage: {
      eyebrow: 'Services',
      title: 'Fertility, gynecology, and laparoscopy support',
      body: 'Choose a care pathway and book an appointment for consultation, diagnosis, treatment planning, or follow-up review.',
      ctaTitle: 'Need help choosing the right care pathway?',
      ctaBody: 'Our front desk can guide you to the right consultation and appointment slot.',
    },
    articlesPage: {
      eyebrow: 'Articles and blogs',
      title: 'Fertility and women wellness notes',
      body: 'Patient education, fertility guidance, laparoscopy explainers, clinic news, and preventive women health guides.',
    },
    galleryPage: {
      eyebrow: 'Gallery',
      title: 'Eva clinic spaces and care moments',
      body: 'View our clinic environment and a short video walkthrough before you visit.',
    },
    contactPage: {
      eyebrow: 'Contact',
      title: 'Book an appointment or speak with our front desk',
      body: 'Send your details and preferred department. The clinic team can confirm available time slots and guide you through the next step.',
      formTitle: 'Appointment request',
      fullName: 'Full name',
      phone: 'Phone',
      email: 'Email',
      age: 'Age',
      category: 'Patient category',
      department: 'Department',
      location: 'Visit location',
      loadingLocations: 'Loading locations...',
      assignLocation: 'Front desk can assign location',
      date: 'Preferred date',
      time: 'Preferred time',
      selectLocationDate: 'Select location and date first',
      loadingTimes: 'Loading available times...',
      selectAvailableTime: 'Select available time',
      noAvailableSlots: 'No available slots for this date',
      booked: 'booked',
      message: 'Message',
      portalNote: 'Use the same email in the patient portal to receive OTP access to your records and appointments.',
      placeholders: {
        name: 'Patient name',
        phone: '+91...',
        email: 'name@email.com',
        age: 'Age',
        message: 'Symptoms, notes, or preferred doctor',
      },
    },
    services: [
      ['Fertility Evaluation', 'Couple-focused assessment, cycle history review, report interpretation, and a clear treatment roadmap.'],
      ['Ovulation Induction & Monitoring', 'Medication-guided ovulation support, follicular monitoring, timing guidance, and follow-up review.'],
      ['IUI / IVF Guidance', 'Step-by-step counseling for assisted conception, investigations, cycle planning, and treatment support.'],
      ['PCOS / PCOD Care', 'Personalized care for irregular periods, hormonal imbalance, fertility concerns, and lifestyle planning.'],
      ['Pregnancy & Antenatal Care', 'Preconception counseling, early pregnancy advice, antenatal visits, and risk review.'],
      ['Laparoscopy & Hysteroscopy', 'Minimally invasive evaluation and treatment for selected gynecological and fertility-related conditions.'],
    ],
    highlights: ['Years of experience', 'Focused specialties', 'Care pathways', 'Location'],
    promises: [
      ['Specialist-led care', 'Consultation guided by obstetrics, gynecology, infertility, IVF, and minimally invasive surgery experience.'],
      ['Clear treatment steps', 'Structured plans for investigations, cycles, procedures, and follow-up care.'],
      ['Sensitive counseling', 'Private, respectful conversations for fertility, women wellness, pregnancy planning, and procedure care.'],
    ],
    successStories: [
      ['Clear counseling from the first visit', 'The consultation felt private and calm. Reports were explained clearly, and we understood the next steps without confusion.', 'Structured fertility evaluation and follow-up plan'],
      ['Confidence before procedure planning', 'The doctor explained why laparoscopy was advised, what to expect, and how recovery would be monitored.', 'Procedure counseling with careful recovery guidance'],
      ['Supportive follow-up care', 'Appointments, medicines, and review dates were explained in simple language. It helped us feel more prepared.', 'Personalized care plan and review schedule'],
    ],
    articles: [
      ['Endometriosis and intimate health: why symptoms deserve sensitive discussion', 'Published Research', 'A patient-friendly summary of research on endometriosis, pain, and female sexual health in Indian women.'],
      ['Unicornuate uterus and pregnancy: careful monitoring can matter', 'Case Report', 'A case-report based explanation of a congenital uterine shape difference and pregnancy follow-up.'],
      ['Before IVF: why uterine cavity assessment may be advised', 'IVF Workup', 'A research-based overview of checking the uterine cavity before IVF treatment planning.'],
    ],
    gallery: ['Warm reception and patient help desk', 'Private consultation room', 'Fertility diagnostics support', 'Eva clinic care walkthrough'],
  },
  hi: {
    languageLabel: 'भाषा',
    nav: { home: 'होम', about: 'हमारे बारे में', services: 'सेवाएं', articles: 'लेख', gallery: 'गैलरी', contact: 'संपर्क' },
    common: {
      bookAppointment: 'अपॉइंटमेंट बुक करें',
      callClinic: 'क्लिनिक कॉल करें',
      whatsapp: 'व्हाट्सऐप',
      contact: 'संपर्क',
      social: 'सोशल',
      readArticle: 'लेख पढ़ें',
      readArticles: 'लेख पढ़ें',
      viewAllServices: 'सभी सेवाएं देखें',
      submitAppointment: 'अपॉइंटमेंट अनुरोध भेजें',
      submitting: 'भेजा जा रहा है...',
    },
    clinic: {
      tagline: 'फर्टिलिटी, महिला स्वास्थ्य और एडवांस लैप्रोस्कोपी',
      emergency: 'सहानुभूतिपूर्ण फर्टिलिटी और स्त्री रोग देखभाल',
      footer: 'फर्टिलिटी, स्त्री रोग और लैप्रोस्कोपी के लिए भरोसेमंद देखभाल, स्पष्ट सलाह और व्यवस्थित फॉलो-अप.',
    },
    home: {
      title: 'ईवा फर्टिलिटी एंड लैप्रोस्कोपी',
      subtitle: 'फर्टिलिटी कंसल्टेशन, महिला स्वास्थ्य, गर्भधारण योजना और मिनिमली इनवेसिव स्त्री रोग प्रक्रियाओं के लिए संवेदनशील विशेषज्ञ देखभाल.',
      programsEyebrow: 'केयर प्रोग्राम',
      programsTitle: 'फर्टिलिटी और महिला स्वास्थ्य सेवाएं',
      articlesEyebrow: 'लेख',
      articlesTitle: 'फर्टिलिटी और महिला स्वास्थ्य जानकारी',
    },
    about: {
      eyebrow: 'हमारे बारे में',
      title: 'भरोसे पर आधारित कोमल फर्टिलिटी और स्त्री रोग देखभाल',
      body: 'ईवा फर्टिलिटी एंड लैप्रोस्कोपी में फर्टिलिटी कंसल्टेशन, महिला स्वास्थ्य, डायग्नोस्टिक्स, विशेषज्ञ फॉलो-अप और लैप्रोस्कोपी देखभाल एक ही जगह मिलती है.',
      cards: ['मरीज पहले', 'योग्य टीम', 'गुणवत्तापूर्ण देखभाल'],
    },
    servicesPage: {
      eyebrow: 'सेवाएं',
      title: 'फर्टिलिटी, स्त्री रोग और लैप्रोस्कोपी सहायता',
      body: 'कंसल्टेशन, जांच, उपचार योजना या फॉलो-अप के लिए सही सेवा चुनें और अपॉइंटमेंट बुक करें.',
      ctaTitle: 'सही सेवा चुनने में मदद चाहिए?',
      ctaBody: 'हमारी फ्रंट डेस्क आपको सही कंसल्टेशन और समय स्लॉट चुनने में मदद करेगी.',
    },
    articlesPage: {
      eyebrow: 'लेख और ब्लॉग',
      title: 'फर्टिलिटी और महिला स्वास्थ्य नोट्स',
      body: 'मरीज शिक्षा, फर्टिलिटी गाइडेंस, लैप्रोस्कोपी जानकारी, क्लिनिक अपडेट और महिला स्वास्थ्य लेख.',
    },
    galleryPage: {
      eyebrow: 'गैलरी',
      title: 'ईवा क्लिनिक और देखभाल की झलक',
      body: 'क्लिनिक का वातावरण और छोटी वीडियो वॉकथ्रू देखें.',
    },
    contactPage: {
      eyebrow: 'संपर्क',
      title: 'अपॉइंटमेंट बुक करें या फ्रंट डेस्क से बात करें',
      body: 'अपनी जानकारी और पसंदीदा सेवा भेजें. हमारी टीम उपलब्ध समय स्लॉट की पुष्टि करेगी.',
      formTitle: 'अपॉइंटमेंट अनुरोध',
      fullName: 'पूरा नाम',
      phone: 'फोन',
      email: 'ईमेल',
      age: 'उम्र',
      category: 'मरीज श्रेणी',
      department: 'विभाग',
      location: 'विजिट लोकेशन',
      loadingLocations: 'लोकेशन लोड हो रही है...',
      assignLocation: 'फ्रंट डेस्क लोकेशन असाइन करेगी',
      date: 'पसंदीदा तारीख',
      time: 'पसंदीदा समय',
      selectLocationDate: 'पहले लोकेशन और तारीख चुनें',
      loadingTimes: 'उपलब्ध समय लोड हो रहे हैं...',
      selectAvailableTime: 'उपलब्ध समय चुनें',
      noAvailableSlots: 'इस तारीख के लिए स्लॉट उपलब्ध नहीं हैं',
      booked: 'बुक',
      message: 'संदेश',
      portalNote: 'रिकॉर्ड और अपॉइंटमेंट देखने के लिए मरीज पोर्टल में यही ईमेल इस्तेमाल करें.',
      placeholders: { name: 'मरीज का नाम', phone: '+91...', email: 'name@email.com', age: 'उम्र', message: 'लक्षण, नोट्स या पसंदीदा डॉक्टर' },
    },
    services: [
      ['फर्टिलिटी कंसल्टेशन', 'व्यक्तिगत मूल्यांकन, ओव्यूलेशन ट्रैकिंग, फर्टिलिटी योजना और कपल काउंसलिंग.'],
      ['IVF और IUI मार्गदर्शन', 'असिस्टेड कंसेप्शन विकल्पों, जांच और उपचार चक्रों के लिए चरणबद्ध सहायता.'],
      ['फर्टिलिटी डायग्नोस्टिक्स', 'हार्मोनल जांच, अल्ट्रासाउंड समन्वय, सीमेन एनालिसिस मार्गदर्शन और रिपोर्ट समीक्षा.'],
      ['लैप्रोस्कोपिक सर्जरी', 'सिस्ट, फाइब्रॉइड, एंडोमेट्रियोसिस और स्त्री रोग स्थितियों के लिए मिनिमली इनवेसिव देखभाल.'],
      ['गर्भधारण योजना', 'प्रीकंसेप्शन केयर, शुरुआती गर्भावस्था सलाह, रिस्क रिव्यू और सतत मार्गदर्शन.'],
      ['महिला वेलनेस', 'मासिक धर्म स्वास्थ्य, PCOS केयर, मेनोपॉज काउंसलिंग और नियमित स्त्री रोग विजिट.'],
    ],
    highlights: ['विशेष देखभाल के वर्ष', 'मार्गदर्शित परिवार', 'केयर पाथवे', 'औसत रेटिंग'],
    promises: [
      ['संवेदनशील काउंसलिंग', 'हर चरण में कपल्स और महिलाओं के लिए निजी, सम्मानजनक बातचीत.'],
      ['स्पष्ट उपचार चरण', 'जांच, उपचार चक्र, प्रक्रियाओं और फॉलो-अप के लिए व्यवस्थित योजना.'],
      ['सुरक्षित प्रक्रियाएं', 'उपचार से पहले और बाद में सुरक्षित क्लिनिकल प्रक्रिया और मार्गदर्शन.'],
    ],
    articles: [
      ['पहले फर्टिलिटी कंसल्टेशन की तैयारी कैसे करें', 'फर्टिलिटी गाइड', 'साइकिल हिस्ट्री, रिपोर्ट, दवाइयां और सवालों की सरल चेकलिस्ट.'],
      ['ओव्यूलेशन विंडो और साइकिल ट्रैकिंग समझें', 'फर्टिलिटी बेसिक्स', 'साइकिल पैटर्न, लक्षण और टेस्टिंग अगली सलाह में कैसे मदद करते हैं.'],
      ['स्त्री रोग देखभाल में लैप्रोस्कोपी कब सलाह दी जाती है', 'लैप्रोस्कोपी', 'मिनिमली इनवेसिव जांच उपचार योजना में कैसे मदद करती है.'],
    ],
    gallery: ['स्वागत कक्ष और हेल्प डेस्क', 'निजी कंसल्टेशन रूम', 'फर्टिलिटी डायग्नोस्टिक्स सहायता', 'ईवा क्लिनिक वॉकथ्रू'],
  },
  mr: {
    languageLabel: 'भाषा',
    nav: { home: 'मुख्यपृष्ठ', about: 'आमच्याबद्दल', services: 'सेवा', articles: 'लेख', gallery: 'गॅलरी', contact: 'संपर्क' },
    common: {
      bookAppointment: 'अपॉइंटमेंट बुक करा',
      callClinic: 'क्लिनिकला कॉल करा',
      whatsapp: 'व्हॉट्सअॅप',
      contact: 'संपर्क',
      social: 'सोशल',
      readArticle: 'लेख वाचा',
      readArticles: 'लेख वाचा',
      viewAllServices: 'सर्व सेवा पहा',
      submitAppointment: 'अपॉइंटमेंट विनंती पाठवा',
      submitting: 'पाठवत आहे...',
    },
    clinic: {
      tagline: 'फर्टिलिटी, महिला आरोग्य आणि प्रगत लॅप्रोस्कोपी',
      emergency: 'संवेदनशील फर्टिलिटी आणि स्त्रीरोग सेवा',
      footer: 'फर्टिलिटी, स्त्रीरोग आणि लॅप्रोस्कोपीसाठी रुग्णकेंद्रित सेवा, स्पष्ट समुपदेशन आणि व्यवस्थित फॉलो-अप.',
    },
    home: {
      title: 'ईवा फर्टिलिटी अँड लॅप्रोस्कोपी',
      subtitle: 'फर्टिलिटी सल्ला, महिला आरोग्य, गर्भधारणा नियोजन आणि मिनिमली इनवेसिव्ह स्त्रीरोग प्रक्रियांसाठी उबदार तज्ज्ञ सेवा.',
      programsEyebrow: 'केअर प्रोग्राम',
      programsTitle: 'फर्टिलिटी आणि महिला आरोग्य सेवा',
      articlesEyebrow: 'लेख',
      articlesTitle: 'फर्टिलिटी आणि महिला आरोग्य मार्गदर्शन',
    },
    about: {
      eyebrow: 'आमच्याबद्दल',
      title: 'विश्वासावर आधारित कोमल फर्टिलिटी आणि स्त्रीरोग सेवा',
      body: 'ईवा फर्टिलिटी अँड लॅप्रोस्कोपीमध्ये फर्टिलिटी सल्ला, महिला आरोग्य, तपासण्या, तज्ज्ञ फॉलो-अप आणि लॅप्रोस्कोपी सेवा एकत्रितपणे मिळतात.',
      cards: ['रुग्ण प्रथम', 'तज्ज्ञ टीम', 'गुणवत्तापूर्ण सेवा'],
    },
    servicesPage: {
      eyebrow: 'सेवा',
      title: 'फर्टिलिटी, स्त्रीरोग आणि लॅप्रोस्कोपी सहाय्य',
      body: 'सल्ला, निदान, उपचार योजना किंवा फॉलो-अपसाठी योग्य सेवा निवडा आणि अपॉइंटमेंट बुक करा.',
      ctaTitle: 'योग्य सेवा निवडण्यासाठी मदत हवी आहे?',
      ctaBody: 'आमची फ्रंट डेस्क तुम्हाला योग्य सल्ला आणि अपॉइंटमेंट स्लॉट निवडण्यास मदत करेल.',
    },
    articlesPage: {
      eyebrow: 'लेख आणि ब्लॉग',
      title: 'फर्टिलिटी आणि महिला आरोग्य नोट्स',
      body: 'रुग्ण शिक्षण, फर्टिलिटी मार्गदर्शन, लॅप्रोस्कोपी माहिती, क्लिनिक अपडेट्स आणि महिला आरोग्य लेख.',
    },
    galleryPage: {
      eyebrow: 'गॅलरी',
      title: 'ईवा क्लिनिक आणि काळजीचे क्षण',
      body: 'भेटीपूर्वी आमचे क्लिनिक वातावरण आणि लहान व्हिडिओ वॉकथ्रू पहा.',
    },
    contactPage: {
      eyebrow: 'संपर्क',
      title: 'अपॉइंटमेंट बुक करा किंवा फ्रंट डेस्कशी बोला',
      body: 'तुमची माहिती आणि पसंतीची सेवा पाठवा. आमची टीम उपलब्ध स्लॉटची पुष्टी करेल.',
      formTitle: 'अपॉइंटमेंट विनंती',
      fullName: 'पूर्ण नाव',
      phone: 'फोन',
      email: 'ईमेल',
      age: 'वय',
      category: 'रुग्ण श्रेणी',
      department: 'विभाग',
      location: 'भेट स्थान',
      loadingLocations: 'स्थान लोड होत आहे...',
      assignLocation: 'फ्रंट डेस्क स्थान देईल',
      date: 'पसंतीची तारीख',
      time: 'पसंतीचा वेळ',
      selectLocationDate: 'प्रथम स्थान आणि तारीख निवडा',
      loadingTimes: 'उपलब्ध वेळा लोड होत आहेत...',
      selectAvailableTime: 'उपलब्ध वेळ निवडा',
      noAvailableSlots: 'या तारखेसाठी स्लॉट उपलब्ध नाहीत',
      booked: 'बुक',
      message: 'संदेश',
      portalNote: 'रेकॉर्ड आणि अपॉइंटमेंट पाहण्यासाठी रुग्ण पोर्टलमध्ये हाच ईमेल वापरा.',
      placeholders: { name: 'रुग्णाचे नाव', phone: '+91...', email: 'name@email.com', age: 'वय', message: 'लक्षणे, नोट्स किंवा पसंतीचा डॉक्टर' },
    },
    services: [
      ['फर्टिलिटी कन्सल्टेशन', 'वैयक्तिक मूल्यांकन, ओव्यूलेशन ट्रॅकिंग, फर्टिलिटी नियोजन आणि कपल काउंसलिंग.'],
      ['IVF आणि IUI मार्गदर्शन', 'असिस्टेड कन्सेप्शन पर्याय, तपासण्या आणि उपचार चक्रांसाठी टप्प्याटप्प्याने मदत.'],
      ['फर्टिलिटी डायग्नोस्टिक्स', 'हार्मोनल तपासणी, अल्ट्रासाउंड समन्वय, सीमेन अॅनालिसिस मार्गदर्शन आणि रिपोर्ट रिव्यू.'],
      ['लॅप्रोस्कोपिक सर्जरी', 'सिस्ट, फायब्रॉइड, एंडोमेट्रियोसिस आणि स्त्रीरोग स्थितींसाठी मिनिमली इनवेसिव्ह सेवा.'],
      ['गर्भधारणा नियोजन', 'प्रीकंसेप्शन केअर, सुरुवातीच्या गर्भधारणेचा सल्ला, रिस्क रिव्यू आणि सातत्यपूर्ण मार्गदर्शन.'],
      ['महिला वेलनेस', 'मासिक पाळी आरोग्य, PCOS केअर, मेनोपॉज काउंसलिंग आणि नियमित स्त्रीरोग भेटी.'],
    ],
    highlights: ['विशेष सेवेची वर्षे', 'मार्गदर्शित कुटुंबे', 'केअर पाथवे', 'सरासरी रेटिंग'],
    promises: [
      ['संवेदनशील समुपदेशन', 'प्रत्येक टप्प्यावर कपल्स आणि महिलांसाठी खाजगी, आदरयुक्त संवाद.'],
      ['स्पष्ट उपचार टप्पे', 'तपासण्या, उपचार चक्र, प्रक्रिया आणि फॉलो-अपसाठी व्यवस्थित योजना.'],
      ['सुरक्षित प्रक्रिया', 'उपचारापूर्वी आणि नंतर सुरक्षित क्लिनिकल प्रक्रिया आणि मार्गदर्शन.'],
    ],
    articles: [
      ['पहिल्या फर्टिलिटी कन्सल्टेशनची तयारी कशी करावी', 'फर्टिलिटी गाइड', 'सायकल हिस्ट्री, रिपोर्ट, औषधे आणि प्रश्नांची सोपी चेकलिस्ट.'],
      ['ओव्यूलेशन विंडो आणि सायकल ट्रॅकिंग समजून घ्या', 'फर्टिलिटी बेसिक्स', 'सायकल पॅटर्न, लक्षणे आणि टेस्टिंग पुढील सल्ल्यात कशी मदत करतात.'],
      ['स्त्रीरोग सेवेत लॅप्रोस्कोपी कधी सुचवली जाते', 'लॅप्रोस्कोपी', 'मिनिमली इनवेसिव्ह तपासणी उपचार नियोजनात कशी मदत करते.'],
    ],
    gallery: ['स्वागत कक्ष आणि हेल्प डेस्क', 'खाजगी कन्सल्टेशन रूम', 'फर्टिलिटी डायग्नोस्टिक्स सहाय्य', 'ईवा क्लिनिक वॉकथ्रू'],
  },
};

Object.assign(dictionaries.en, {
  labels: {
    leadConsultant: 'Lead Consultant',
    careFocus: 'Eva care focus',
    doctorProfile: 'Doctor profile',
    clinicalFocusAreas: 'Clinical focus areas',
    patientFriendlyAbstract: 'Patient-friendly abstract',
    patientTakeaway: 'Patient takeaway',
    viewSource: 'View source',
    experienceSuffix: 'experience',
    achievements: 'Achievements',
    conferencesAttended: 'Conferences Attended',
  },
  doctor: {
    name: 'Dr. Raveendra Gondhali',
    role: 'Consultant Obstetrician, Gynaecologist & IVF Specialist',
    qualifications: 'MBBS, MS (OBGY), F. MAS',
    experience: '25+ years',
    note: 'Patient-first consultation with clear counseling, privacy, and structured follow-up.',
    focusTitle: 'Specialized support for fertility, IVF guidance, and minimally invasive gynecology care',
    aboutNote: 'Practicing at Eva Fertility & Laparoscopy, Silver Birch Multispeciality Hospital, Thergaon, with a focus on fertility consultation, women wellness, pregnancy planning, and minimally invasive gynecology care.',
    expertise: [
      'Fertility evaluation and infertility treatment',
      'IVF and IUI guidance',
      'Ovulation induction and monitoring',
      'PCOS and menstrual health care',
      'Diagnostic and operative laparoscopy',
      'Hysteroscopy diagnosis and treatment',
      'Pregnancy care and antenatal support',
    ],
  },
});

Object.assign(dictionaries.hi, {
  home: {
    ...dictionaries.hi.home,
    successEyebrow: 'मरीजों के विचार',
    successTitle: 'हमारी सफलता की कहानियां',
    successSubtitle: 'गोपनीय मरीज प्रतिक्रिया, जिसमें संवाद, आराम और व्यवस्थित फॉलो-अप पर ध्यान है.',
  },
  labels: {
    leadConsultant: 'मुख्य सलाहकार',
    careFocus: 'ईवा केयर फोकस',
    doctorProfile: 'डॉक्टर प्रोफाइल',
    clinicalFocusAreas: 'क्लिनिकल फोकस क्षेत्र',
    patientFriendlyAbstract: 'मरीजों के लिए सरल सारांश',
    patientTakeaway: 'मरीज के लिए मुख्य बात',
    viewSource: 'स्रोत देखें',
    experienceSuffix: 'अनुभव',
    achievements: 'उपलब्धियां',
    conferencesAttended: 'सम्मेलन सहभागिता',
  },
  doctor: {
    name: 'डॉ. रवींद्र गोंधली',
    role: 'कंसल्टेंट ऑब्स्टेट्रिशियन, गायनेकोलॉजिस्ट और IVF स्पेशलिस्ट',
    qualifications: 'MBBS, MS (OBGY), F. MAS',
    experience: '25+ वर्ष',
    note: 'गोपनीयता, ध्यान से सुनने और स्पष्ट फॉलो-अप के साथ मरीज-केंद्रित परामर्श.',
    focusTitle: 'फर्टिलिटी, IVF मार्गदर्शन और मिनिमली इनवेसिव स्त्रीरोग देखभाल के लिए विशेषज्ञ सहायता',
    aboutNote: 'ईवा फर्टिलिटी एंड लैप्रोस्कोपी, सिल्वर बर्च मल्टीस्पेशलिटी हॉस्पिटल, थेरगांव में फर्टिलिटी कंसल्टेशन, महिला स्वास्थ्य, गर्भधारण योजना और मिनिमली इनवेसिव स्त्रीरोग देखभाल पर केंद्रित सेवा.',
    expertise: [
      'फर्टिलिटी मूल्यांकन और बांझपन उपचार',
      'IVF और IUI मार्गदर्शन',
      'ओव्यूलेशन इंडक्शन और मॉनिटरिंग',
      'PCOS और मासिक धर्म स्वास्थ्य देखभाल',
      'डायग्नोस्टिक और ऑपरेटिव लैप्रोस्कोपी',
      'हिस्टेरोस्कोपी जांच और उपचार',
      'गर्भावस्था और एंटिनेटल सहायता',
    ],
  },
  highlights: ['अनुभव के वर्ष', 'विशेषज्ञ क्षेत्र', 'केयर पाथवे', 'स्थान'],
  articles: [
    [
      'एंडोमेट्रियोसिस और अंतरंग स्वास्थ्य: लक्षणों पर संवेदनशील चर्चा क्यों जरूरी है',
      'प्रकाशित शोध',
      'एंडोमेट्रियोसिस, दर्द और भारतीय महिलाओं के यौन स्वास्थ्य पर शोध का सरल सारांश.',
      'इस अध्ययन में लैप्रोस्कोपी से पुष्टि किए गए एंडोमेट्रियोसिस वाली महिलाओं में यौन स्वास्थ्य पर प्रभाव देखा गया. इसमें इच्छा, उत्तेजना, लुब्रिकेशन, ऑर्गेज्म, संतुष्टि और दर्द जैसे पहलुओं का आकलन किया गया. शोध में पाया गया कि कई मरीजों में यौन समस्या आम थी और बीमारी की गंभीरता के साथ यह बढ़ सकती है. मरीजों के लिए संदेश है कि पीरियड दर्द, पेल्विक दर्द, संबंध के दौरान दर्द और फर्टिलिटी चिंता पर डॉक्टर से खुलकर बात करनी चाहिए.',
      'यदि दर्द या एंडोमेट्रियोसिस आपके जीवन, रिश्ते या फर्टिलिटी योजना को प्रभावित कर रहा है, तो निजी परामर्श उपचार और जीवन-गुणवत्ता दोनों को जोड़ सकता है.',
    ],
    [
      'यूनिकॉर्नुएट यूटेरस और गर्भावस्था: सावधानीपूर्वक निगरानी क्यों मायने रखती है',
      'केस रिपोर्ट',
      'जन्मजात गर्भाशय आकार में अंतर और गर्भावस्था फॉलो-अप की सरल जानकारी.',
      'इस केस रिपोर्ट में यूनिकॉर्नुएट यूटेरस वाली गर्भावस्था पर चर्चा है. यह जन्मजात स्थिति है जिसमें गर्भाशय एक तरफ से विकसित होता है. ऐसी स्थिति बांझपन, गर्भपात, समय से पहले डिलीवरी, ब्रीच प्रस्तुति या बच्चे की वृद्धि से जुड़ी चिंताओं से संबंधित हो सकती है. रिपोर्ट समय पर निदान, एंटिनेटल निगरानी और योजनाबद्ध प्रसूति देखभाल के महत्व को बताती है.',
      'यदि आपकी सोनोग्राफी या पुराने रिपोर्ट में गर्भाशय की संरचना से जुड़ी बात लिखी है, तो उसे परामर्श में जरूर लाएं.',
    ],
    [
      'IVF से पहले: यूटेराइन कैविटी जांच कब उपयोगी हो सकती है',
      'IVF वर्कअप',
      'IVF योजना से पहले गर्भाशय की अंदरूनी कैविटी जांच पर शोध आधारित सरल जानकारी.',
      'इस प्रकाशन में IVF से पहले 3D ट्रांसवजाइनल अल्ट्रासोनोग्राफी और ऑफिस हिस्टेरोस्कोपी की तुलना की गई. मरीजों के लिए आसान भाषा में, गर्भाशय की कैविटी वही जगह है जहां भ्रूण को इम्प्लांट होना होता है. पॉलिप, सेप्टम, चिपकाव, फाइब्रॉइड या अन्य कैविटी समस्या पहचानना फर्टिलिटी योजना में मदद कर सकता है.',
      'IVF या फर्टिलिटी उपचार से पहले डॉक्टर से पूछें कि कौन से रिपोर्ट जरूरी हैं और क्या आपके लिए यूटेराइन कैविटी मूल्यांकन उचित है.',
    ],
    [
      'स्त्रीरोग सर्जरी में सुरक्षा जांच: सिस्टोयूरेथ्रोस्कोपी को समझें',
      'सर्जिकल सेफ्टी',
      'कुछ स्त्रीरोग सर्जरी में मूत्रमार्ग/ब्लैडर सुरक्षा जांच क्यों की जा सकती है.',
      'यह शोध रिकॉर्ड स्त्रीरोग सर्जरी के दौरान निचले मूत्रमार्ग की चोट पहचानने में यूनिवर्सल सिस्टोयूरेथ्रोस्कोपी की भूमिका पर केंद्रित है. मरीजों के लिए, सिस्टोयूरेथ्रोस्कोपी ब्लैडर और यूरेथ्रा को छोटे कैमरे से देखने की प्रक्रिया है. कुछ सर्जरी में यह टीम को प्रक्रिया पूरी करने से पहले सुरक्षा जांच में मदद कर सकती है.',
      'लैप्रोस्कोपी या स्त्रीरोग सर्जरी से पहले पूछें कि कौन सी सुरक्षा जांच की जाएगी और डिस्चार्ज के बाद किन लक्षणों पर ध्यान देना है.',
    ],
  ],
});

Object.assign(dictionaries.mr, {
  home: {
    ...dictionaries.mr.home,
    successEyebrow: 'रुग्णांचे विचार',
    successTitle: 'आमच्या यशोगाथा',
    successSubtitle: 'गोपनीय रुग्ण प्रतिक्रिया, ज्यात संवाद, आराम आणि व्यवस्थित फॉलो-अपवर भर आहे.',
  },
  labels: {
    leadConsultant: 'मुख्य सल्लागार',
    careFocus: 'ईवा केअर फोकस',
    doctorProfile: 'डॉक्टर प्रोफाइल',
    clinicalFocusAreas: 'क्लिनिकल फोकस क्षेत्र',
    patientFriendlyAbstract: 'रुग्णांसाठी सोपा सारांश',
    patientTakeaway: 'रुग्णांसाठी महत्त्वाची गोष्ट',
    viewSource: 'स्रोत पहा',
    experienceSuffix: 'अनुभव',
    achievements: 'उपलब्धी',
    conferencesAttended: 'परिषद सहभाग',
  },
  doctor: {
    name: 'डॉ. रवींद्र गोंधळी',
    role: 'कन्सल्टंट ऑब्स्टेट्रिशियन, गायनेकोलॉजिस्ट आणि IVF स्पेशलिस्ट',
    qualifications: 'MBBS, MS (OBGY), F. MAS',
    experience: '25+ वर्षे',
    note: 'गोपनीयता, काळजीपूर्वक ऐकणे आणि स्पष्ट फॉलो-अप यासह रुग्ण-केंद्रित सल्ला.',
    focusTitle: 'फर्टिलिटी, IVF मार्गदर्शन आणि मिनिमली इनवेसिव्ह स्त्रीरोग सेवांसाठी तज्ज्ञ मदत',
    aboutNote: 'ईवा फर्टिलिटी अँड लैप्रोस्कोपी, सिल्वर बर्च मल्टीस्पेशलिटी हॉस्पिटल, थेरगाव येथे फर्टिलिटी सल्ला, महिला आरोग्य, गर्भधारणा नियोजन आणि मिनिमली इनवेसिव्ह स्त्रीरोग सेवांवर केंद्रित सेवा.',
    expertise: [
      'फर्टिलिटी मूल्यांकन आणि वंध्यत्व उपचार',
      'IVF आणि IUI मार्गदर्शन',
      'ओव्ह्युलेशन इंडक्शन आणि मॉनिटरिंग',
      'PCOS आणि मासिक पाळी आरोग्य सेवा',
      'डायग्नोस्टिक आणि ऑपरेटिव्ह लैप्रोस्कोपी',
      'हिस्टेरोस्कोपी निदान आणि उपचार',
      'गर्भधारणा आणि अँटिनेटल सपोर्ट',
    ],
  },
  highlights: ['अनुभवाची वर्षे', 'विशेषज्ञ क्षेत्रे', 'केअर पाथवे', 'स्थान'],
  articles: [
    [
      'एंडोमेट्रिओसिस आणि अंतरंग आरोग्य: लक्षणांवर संवेदनशील चर्चा का आवश्यक आहे',
      'प्रकाशित संशोधन',
      'एंडोमेट्रिओसिस, वेदना आणि भारतीय महिलांच्या लैंगिक आरोग्यावर संशोधनाचा सोपा सारांश.',
      'या अभ्यासात लैप्रोस्कोपीने निदान झालेल्या एंडोमेट्रिओसिस असलेल्या महिलांमध्ये लैंगिक आरोग्यावर होणारा परिणाम पाहिला. इच्छा, उत्तेजना, लुब्रिकेशन, ऑर्गॅझम, समाधान आणि वेदना यांसारख्या भागांचे मूल्यांकन केले गेले. संशोधनात लैंगिक समस्या सामान्य असू शकतात आणि आजाराची तीव्रता वाढल्यास त्या वाढू शकतात असे दिसले. रुग्णांसाठी संदेश असा की पाळीतील वेदना, पेल्विक वेदना, संबंधाच्या वेळी वेदना आणि फर्टिलिटी चिंता डॉक्टरांशी मोकळेपणाने बोलाव्यात.',
      'जर वेदना किंवा एंडोमेट्रिओसिस तुमच्या जीवनावर, नात्यावर किंवा फर्टिलिटी नियोजनावर परिणाम करत असेल, तर खासगी सल्ला उपचार आणि जीवनगुणवत्ता दोन्ही जोडू शकतो.',
    ],
    [
      'युनिकॉर्नुएट युटेरस आणि गर्भधारणा: काळजीपूर्वक मॉनिटरिंग महत्त्वाचे',
      'केस रिपोर्ट',
      'जन्मजात गर्भाशयाच्या आकारातील फरक आणि गर्भधारणा फॉलो-अपची सोपी माहिती.',
      'या केस रिपोर्टमध्ये युनिकॉर्नुएट युटेरस असलेल्या गर्भधारणेवर चर्चा आहे. ही जन्मजात स्थिती असून गर्भाशय एका बाजूने विकसित होते. अशा स्थितीचा संबंध वंध्यत्व, गर्भपात, अकाली प्रसूती, ब्रीच प्रस्तुती किंवा बाळाच्या वाढीशी संबंधित चिंतांशी असू शकतो. रिपोर्ट वेळेवर निदान, अँटिनेटल मॉनिटरिंग आणि नियोजित प्रसूती सेवांचे महत्त्व सांगतो.',
      'सोनोग्राफी किंवा जुन्या रिपोर्टमध्ये गर्भाशयाच्या रचनेबद्दल काही नमूद असल्यास तो रिपोर्ट सल्ल्यासाठी नक्की आणा.',
    ],
    [
      'IVF पूर्वी: युटेराइन कॅव्हिटी तपासणी कधी उपयोगी ठरू शकते',
      'IVF वर्कअप',
      'IVF नियोजनापूर्वी गर्भाशयाच्या आतील कॅव्हिटी तपासणीबद्दल संशोधनाधारित सोपी माहिती.',
      'या प्रकाशनात IVF पूर्वी 3D ट्रान्सवजाइनल अल्ट्रासोनोग्राफी आणि ऑफिस हिस्टेरोस्कोपीची तुलना केली आहे. रुग्णांसाठी सोप्या भाषेत, गर्भाशयाची कॅव्हिटी ही भ्रूण इम्प्लांट होण्याची जागा आहे. पॉलिप, सेप्टम, चिकटलेले भाग, फायब्रॉइड किंवा इतर कॅव्हिटी समस्या ओळखणे फर्टिलिटी नियोजनात मदत करू शकते.',
      'IVF किंवा फर्टिलिटी उपचारांपूर्वी कोणते रिपोर्ट आवश्यक आहेत आणि तुमच्यासाठी युटेराइन कॅव्हिटी मूल्यांकन योग्य आहे का हे डॉक्टरांना विचारा.',
    ],
    [
      'स्त्रीरोग शस्त्रक्रियेत सुरक्षा तपासणी: सिस्टोयूरेथ्रोस्कोपी समजून घ्या',
      'सर्जिकल सेफ्टी',
      'काही स्त्रीरोग शस्त्रक्रियांमध्ये मूत्रमार्ग/ब्लॅडर सुरक्षा तपासणी का केली जाऊ शकते.',
      'हा संशोधन रेकॉर्ड स्त्रीरोग शस्त्रक्रियेदरम्यान खालच्या मूत्रमार्गाच्या इजा ओळखण्यासाठी यूनिव्हर्सल सिस्टोयूरेथ्रोस्कोपीच्या भूमिकेवर केंद्रित आहे. रुग्णांसाठी, सिस्टोयूरेथ्रोस्कोपी म्हणजे ब्लॅडर आणि यूरेथ्रा छोट्या कॅमेर्‍याने पाहण्याची प्रक्रिया. काही शस्त्रक्रियांमध्ये ती प्रक्रिया पूर्ण करण्यापूर्वी सुरक्षा तपासणीस मदत करू शकते.',
      'लैप्रोस्कोपी किंवा स्त्रीरोग शस्त्रक्रियेपूर्वी कोणत्या सुरक्षा तपासण्या होणार आहेत आणि डिस्चार्जनंतर कोणती लक्षणे पाहायची हे विचारा.',
    ],
  ],
});

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('public_site_language') || 'en');
  const value = useMemo(() => {
    const dictionary = dictionaries[language] || dictionaries.en;
    const setAndStoreLanguage = (nextLanguage) => {
      setLanguage(nextLanguage);
      localStorage.setItem('public_site_language', nextLanguage);
    };
    return { language, setLanguage: setAndStoreLanguage, dictionary };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}

export const languageOptions = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'mr', label: 'मराठी' },
];
